console.log("hello my name isg to understand git")
console.log("this is master branch")
console.log("commiting in master")
console.log("hello my name is sai and trying to understand git")
console.log("this  branch")
console.log("commiting in master")
console.log("hello my name is sai and trying to understand git")
console.log("this is master branch")

console.log("this is master branch")
console.log("commiting in master")console.log("hello my name is sai and trying to understand git")
console.log("this is master branch")
console.log("commiting in master")
console.log("hello my namederstand git")
console.log("this is master branch")
console.log("commi")
