
console.log("commivting in master")
console.log("fsdsv my name is sai and vasdfsdftrying to understand git")
console.log("this  branch")
console.log("commiting in master")
console.log("hello my name is saisdf and trying to understand git")
console.log("this isfsdfssfsf master branch")
console.log("hello my name is sai and trying to understand git")
console.log("this is master branch")
console.log("this is master branch")
console.log("commiting in master")
console.log("hello my name is sai and trying to understand git")
console.log("this is master branch")
console.log("commiting in master")
console.log("hello my namederstand git")
